-- Entity 1: MB_MENU_ITEMS
CREATE TABLE MB_MENU_ITEMS (
    item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    item_name VARCHAR2(50) NOT NULL,            -- e.g., 'Nasi Lemak MB', 'Lucky Plate' - 20 chars max
    item_description VARCHAR2(100),             -- e.g., '2-pc Chicken, Mashed Potato...' - 60 chars max
    price NUMBER(4, 2) NOT NULL                 -- e.g., 17.50, 10.90 - Max 99.99
);

-- Entity 2: MB_CUSTOMERS
CREATE TABLE MB_CUSTOMERS (
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(30) NOT NULL,           -- e.g., 'Muhammad', 'Samantha' - 8 chars max
    last_name VARCHAR2(30) NOT NULL,            -- e.g., 'Abdul Rahman', 'Smith' - 12 chars max
    email VARCHAR2(70),                         -- e.g., 'name.surname@example.com' - 25 chars max + domain
    phone_number VARCHAR2(15)                   -- e.g., '012-3456789' - 11 chars max
);

-- Entity 3: MB_STAFF
CREATE TABLE MB_STAFF (
    staff_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(30) NOT NULL,
    last_name VARCHAR2(30) NOT NULL,
    position VARCHAR2(30),                      -- e.g., 'Manager', 'Service Crew' - 19 chars max
    hire_date DATE
);

-- Entity 4: MB_OUTLETS
CREATE TABLE MB_OUTLETS (
    outlet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    outlet_name VARCHAR2(50) NOT NULL,          -- e.g., 'MB AEON Mall Kinta City' - 23 chars max
    address VARCHAR2(150),                      -- e.g., 'Lot F01, AEON Mall Kinta City, Jalan Teh Khuan Lye' - 55 chars max
    city VARCHAR2(30),                          -- e.g., 'Kuala Lumpur', 'Ipoh' - 12 chars max
    state VARCHAR2(30)                          -- e.g., 'W.P. Kuala Lumpur', 'Perak' - 17 chars max
);

-- Entity 5: MB_ORDERS
CREATE TABLE MB_ORDERS (
    order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_date TIMESTAMP NOT NULL,
    total_amount NUMBER(6, 2) NOT NULL,         -- e.g., 63.10, 55.20 - Max 9999.99
    payment_method VARCHAR2(20)                 -- e.g., 'Credit Card', 'E-Wallet' - 11 chars max
);

-- Entity 6: MB_SUPPLIERS
CREATE TABLE MB_SUPPLIERS (
    supplier_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(50) NOT NULL,        -- e.g., 'Chicken Farm Sdn Bhd' - 20 chars max
    contact_person VARCHAR2(50),                -- e.g., 'Mr. Wong', 'Ms. Devi' - 8 chars max
    phone_number VARCHAR2(15)
);

-- Entity 7: MB_INVENTORY
CREATE TABLE MB_INVENTORY (
    inventory_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    item_name VARCHAR2(50) NOT NULL,            -- e.g., 'Frozen Chicken', 'Paper Napkins' - 13 chars max
    quantity NUMBER(6) NOT NULL,                -- e.g., 1000 (napkins), 500 (chicken) - Max 999999
    unit_of_measure VARCHAR2(20)                -- e.g., 'kg', 'liters', 'pieces', 'heads' - 7 chars max
);

-- Entity 8: MB_PROMOTIONS
CREATE TABLE MB_PROMOTIONS (
    promotion_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    promotion_name VARCHAR2(50) NOT NULL,       -- e.g., 'Year-End Holiday Promotion' - 26 chars max
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    discount_percentage NUMBER(4, 2)            -- e.g., 100.00 (for free), 15.00 - Max 99.99
);

-- Entity 9: MB_FRANCHISEES
CREATE TABLE MB_FRANCHISEES (
    franchisee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    franchisee_name VARCHAR2(70) NOT NULL,      -- e.g., 'Delicious Ventures Sdn Bhd' - 26 chars max
    contact_email VARCHAR2(70),                 -- e.g., 'contact@megabites.com' - 21 chars max
    agreement_date DATE
);

-- Entity 10: MB_DELIVERY_DRIVERS
CREATE TABLE MB_DELIVERY_DRIVERS (
    driver_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(30) NOT NULL,
    last_name VARCHAR2(30) NOT NULL,
    vehicle_type VARCHAR2(20)                   -- e.g., 'Motorcycle', 'Car' - 10 chars max
);

-- Entity 11: MB_FEEDBACK
CREATE TABLE MB_FEEDBACK (
    feedback_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(70),                 -- e.g., 'Ahmad Rosli', 'Melissa Wong' - 12 chars max (considering full name)
    rating NUMBER(1, 0) CHECK (rating >= 1 AND rating <= 5),
    comments VARCHAR2(300)                      -- e.g., 'Great food and fast service!' - 55 chars max (allowing for longer comments)
);

-- Entity 12: MB_INGREDIENTS
CREATE TABLE MB_INGREDIENTS (
    ingredient_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ingredient_name VARCHAR2(50) NOT NULL,      -- e.g., 'Flour (All-Purpose)', 'Cooking Oil (Palm)' - 20 chars max
    unit_cost NUMBER(5, 2)                      -- e.g., 8.50, 6.20 - Max 999.99
);

-- Entity 13: MB_EQUIPMENT
CREATE TABLE MB_EQUIPMENT (
    equipment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    equipment_name VARCHAR2(50) NOT NULL,       -- e.g., 'Chicken Pressure Cooker', 'Walk-in Cooler' - 23 chars max
    last_maintenance_date DATE,
    next_maintenance_date DATE
);

-- Entity 14: MB_TRAINING_MODULES
CREATE TABLE MB_TRAINING_MODULES (
    module_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    module_name VARCHAR2(70) NOT NULL,          -- e.g., 'Customer Service Excellence', 'Waste Reduction Practices' - 27 chars max
    duration_hours NUMBER(4, 1),                -- e.g., 4.0, 1.5 - Max 999.9 hours
    last_updated DATE
);

-- Entity 15: MB_MARKETING_CAMPAIGNS
CREATE TABLE MB_MARKETING_CAMPAIGNS (
    campaign_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    campaign_name VARCHAR2(70) NOT NULL,        -- e.g., 'Anniversary Mega Sale', 'Digital Drive Thru Launch' - 27 chars max
    budget NUMBER(12, 2),                       -- e.g., 80000.00, 75000.00 - Max 9999999999.99 (allowing for large budgets)
    start_date DATE,
    end_date DATE
);

-- Entity 16: MB_LOYALTY_PROGRAMS
CREATE TABLE MB_LOYALTY_PROGRAMS (
    program_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    program_name VARCHAR2(50) NOT NULL,         -- e.g., 'New Member Welcome Bonus', 'MB Rewards Club' - 24 chars max
    points_per_dollar NUMBER(3, 2),             -- e.g., 0.10, 0.20 - Max 9.99
    description VARCHAR2(150)                   -- e.g., 'Earn points with every purchase for exclusive discounts.' - 57 chars max
);

-- Entity 17: MB_PACKAGING_MATERIALS
CREATE TABLE MB_PACKAGING_MATERIALS (
    material_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    material_name VARCHAR2(50) NOT NULL,        -- e.g., 'Delivery Carrier Bag', 'Chicken Box (Large)' - 20 chars max
    cost_per_unit NUMBER(4, 2)                  -- e.g., 0.50, 0.30 - Max 99.99
);

-- Entity 18: MB_RECIPES
CREATE TABLE MB_RECIPES (
    recipe_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    recipe_name VARCHAR2(50) NOT NULL,          -- e.g., 'Mashed Potato Gravy', 'Nasi Lemak Sambal' - 19 chars max
    preparation_time_minutes NUMBER(4),         -- e.g., 20, 10 - Max 9999 minutes
    servings NUMBER(4)                          -- e.g., 10, 8 - Max 9999 servings
);

-- Entity 19: MB_WASTE_RECORDS
CREATE TABLE MB_WASTE_RECORDS (
    waste_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    record_date DATE NOT NULL,
    item_wasted VARCHAR2(50) NOT NULL,          -- e.g., 'Fried Chicken', 'Burger Buns' - 13 chars max
    quantity_wasted NUMBER(5),                  -- e.g., 5, 2 - Max 99999 units/items
    reason VARCHAR2(100)                        -- e.g., 'Overcooked', 'Expired', 'Equipment Malfunction' - 25 chars max
);

-- Entity 20: MB_UTILITIES
CREATE TABLE MB_UTILITIES (
    utility_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    utility_type VARCHAR2(30) NOT NULL,         -- e.g., 'Electricity', 'Waste Management' - 16 chars max
    billing_month DATE NOT NULL,
    amount_paid NUMBER(9, 2)                    -- e.g., 1500.00, 350.00 - Max 9999999.99 (allowing for higher bills)
);