
- =================================================================
-- DROP JUNCTION (MANY-TO-MANY) TABLES
-- =================================================================

DROP TABLE IngredientInventory CASCADE CONSTRAINTS;
DROP TABLE FeedbackIngredient CASCADE CONSTRAINTS;
DROP TABLE LogisticFeedback CASCADE CONSTRAINTS;
DROP TABLE LogisticIngredient CASCADE CONSTRAINTS;
DROP TABLE TransactionFeedback CASCADE CONSTRAINTS;
DROP TABLE TransactionLogistic CASCADE CONSTRAINTS;
DROP TABLE TransactionIngredient CASCADE CONSTRAINTS;
DROP TABLE TransactionTransaction CASCADE CONSTRAINTS;
DROP TABLE OrderIngredient CASCADE CONSTRAINTS;
DROP TABLE OrderTransaction CASCADE CONSTRAINTS;
DROP TABLE ProductFeedback CASCADE CONSTRAINTS;
DROP TABLE ProductIngredient CASCADE CONSTRAINTS;
DROP TABLE ProductMenu CASCADE CONSTRAINTS;
DROP TABLE ProductOrder CASCADE CONSTRAINTS;
DROP TABLE ProductTransaction CASCADE CONSTRAINTS;
DROP TABLE DocumentDocument CASCADE CONSTRAINTS;
DROP TABLE TrainingCertificate CASCADE CONSTRAINTS;
DROP TABLE EmployeeKitchen CASCADE CONSTRAINTS;
DROP TABLE EmployeeTraining CASCADE CONSTRAINTS;
DROP TABLE EmployeeDocument CASCADE CONSTRAINTS;
DROP TABLE EmployeeIngredient CASCADE CONSTRAINTS;
DROP TABLE EmployeeProduct CASCADE CONSTRAINTS;
DROP TABLE EmployeeMenu CASCADE CONSTRAINTS;
DROP TABLE EmployeeInventory CASCADE CONSTRAINTS;
DROP TABLE EmployeeEmployee CASCADE CONSTRAINTS;
DROP TABLE SupplierIngredient CASCADE CONSTRAINTS;
DROP TABLE SupplierLogistic CASCADE CONSTRAINTS;
DROP TABLE CustomerProduct CASCADE CONSTRAINTS;
DROP TABLE CustomerMenu CASCADE CONSTRAINTS;
DROP TABLE PersonPerson CASCADE CONSTRAINTS;
DROP TABLE PersonFeedback CASCADE CONSTRAINTS;
DROP TABLE PersonTransaction CASCADE CONSTRAINTS;
DROP TABLE PersonOrder CASCADE CONSTRAINTS;
DROP TABLE OutletDocument CASCADE CONSTRAINTS;
DROP TABLE OutletPerson CASCADE CONSTRAINTS;

-- =================================================================
-- DROP ENTITY TABLES
-- =================================================================

DROP TABLE Outlet CASCADE CONSTRAINTS;
DROP TABLE Person CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Supplier CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE Manager CASCADE CONSTRAINTS;
DROP TABLE Training CASCADE CONSTRAINTS;
DROP TABLE Document CASCADE CONSTRAINTS;
DROP TABLE Certificate CASCADE CONSTRAINTS;
DROP TABLE Timesheet CASCADE CONSTRAINTS;
DROP TABLE Salary CASCADE CONSTRAINTS;
DROP TABLE Menu CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE OrderTBL CASCADE CONSTRAINTS;
DROP TABLE Transaction CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Purchase CASCADE CONSTRAINTS;
DROP TABLE Kitchen CASCADE CONSTRAINTS;
DROP TABLE Ingredient CASCADE CONSTRAINTS;
DROP TABLE Inventory CASCADE CONSTRAINTS;
DROP TABLE Logistic CASCADE CONSTRAINTS;
DROP TABLE Feedback CASCADE CONSTRAINTS;